[build]
  command = "npm run build"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
  NEXT_PUBLIC_APP_URL = "https://rms.codelitsstudio.com"
  AUTH_SECRET = "@auth_secret"

[[edge_functions]]
  path = "/*"
  function = "middleware"
