[build]
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18.18.2"
  NEXT_PUBLIC_APP_URL = "https://rms.codelitsstudio.com"


[[edge_functions]]
  path = "/*"
  function = "middleware"